CONF_MAP = {
    "ACC": ["ACC", "Atlantic Coast", "Atlantic Coast Conference"],
    "America East": ["America East", "AE", "AmEast", "America East Conference"],
    "American": [
        "American",
        "AAC",
        "The American",
        "American Athletic",
        "American Athletic Conference",
    ],
    "ASUN": ["ASUN", "Atlantic Sun", "Atlantic Sun Conference"],
    "Big 12": ["Big 12", "Big XII", "B12", "Big Twelve"],
    "Big East": ["Big East", "BE", "Big East Conference"],
    "Big Sky": ["Big Sky", "BSky", "Big Sky Conference"],
    "Big South": ["Big South", "BSouth", "Big South Conference"],
    "Big Ten": ["Big Ten", "B1G", "Big 10", "Big Ten Conference"],
    "Big West": ["Big West", "BWest", "Big West Conference"],
    "CAA": ["CAA", "Colonial", "Colonial Athletic", "Colonial Athletic Association"],
    "Conference USA": ["Conference USA", "C-USA", "CUSA"],
    "Horizon": ["Horizon", "Horizon League"],
    "Ivy League": ["Ivy", "Ivy League"],
    "MAAC": [
        "MAAC",
        "Metro Atlantic",
        "Metro Atlantic Athletic",
        "Metro Atlantic Athletic Conference",
    ],
    "MAC": ["MAC", "Mid-American", "Mid-American Conference"],
    "MEAC": ["MEAC", "Mid-Eastern Athletic", "Mid-Eastern Athletic Conference"],
    "Missouri Valley": ["MVC", "Missouri Valley", "Missouri Valley Conference"],
    "Mountain West": ["MW", "MWC", "Mountain West", "Mountain West Conference"],
    "NEC": ["NEC", "Northeast", "Northeast Conference"],
    "Ohio Valley": ["OVC", "Ohio Valley", "Ohio Valley Conference"],
    "Patriot": ["Patriot", "Patriot League"],
    "SEC": ["SEC", "Southeastern", "Southeastern Conference"],
    "SoCon": ["SoCon", "Southern", "Southern Conference"],
    "Southland": ["Southland", "Southland Conference"],
    "SWAC": ["SWAC", "Southwestern Athletic", "Southwestern Athletic Conference"],
    "Summit": ["Summit", "Summit League"],
    "Sun Belt": ["Sun Belt", "Sun Belt Conference", "SBC"],
    "WAC": ["WAC", "Western Athletic", "Western Athletic Conference"],
    "West Coast": ["WCC", "West Coast", "West Coast Conference"],
}
