name: cbb-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # Core math / data
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - statsmodels

  # HTML / rendering (pandas Styler)
  - lxml
  - jinja2


  # Visualization (NO GUI / NO ALSA)
  - matplotlib-base
  - seaborn
  - plotly

  # Utilitiesy
  - requests
  - tqdm
  - pyyaml
  - python-dateutil
  - pytz

 # Pip-only dependencies
  - pip:
      - kagglehub
      - beautifulsoup4
      - playwright