CONF_MAP = {
    "ACC": ["ACC", "Atlantic Coast", "Atlantic Coast Conference", "Atlantic Coast Women"],
    "America East": ["America East", "AE", "AmEast", "America East Conference"],
    "American": [
        "American",
        "AAC",
        "The American",
        "American Athletic",
        "American Athletic Conference",
    ],
    "A10" : ["Atlantic 10", "Atlantic 10 Women", "A10", "Atlantic Ten"],
    "ASUN": ["ASUN", "Atlantic Sun", "Atlantic Sun Conference", "Atlantic Sun Women"],
    "Big 12": ["Big 12", "Big XII", "B12", "Big Twelve", "Big 12 Women"],
    "Big East": ["Big East", "BE", "Big East Conference", "Big East Women"],
    "Big Sky": ["Big Sky", "BSky", "Big Sky Conference", "Big Sky Women"],
    "Big South": ["Big South", "BSouth", "Big South Conference", "Big South Women"],
    "Big Ten": ["Big Ten", "B1G", "Big 10", "Big Ten Conference", "Big Ten Women"],
    "Big West": ["Big West", "BWest", "Big West Conference", "Big West Women"],
    "CAA": ["CAA", "Colonial", "Colonial Athletic", "Colonial Athletic Association"],
    "Conference USA": ["Conference USA", "C-USA", "CUSA"],
    "Horizon": ["Horizon", "Horizon League", "Horizon Women"],
    "Ivy League": ["Ivy", "Ivy League"],
    "MAAC": [
        "MAAC",
        "Metro Atlantic",
        "Metro Atlantic Athletic",
        "Metro Atlantic Athletic Conference",
        "Metro Atlantic Athletic Women"
    ],
    "MAC": ["MAC", "Mid-American", "Mid-American Conference"],
    "MEAC": ["MEAC", "Mid-Eastern Athletic", "Mid-Eastern Athletic Conference"],
    "Missouri Valley": ["MVC", "Missouri Valley", "Missouri Valley Conference", "Missouri Valley Women"],
    "Mountain West": ["MW", "MWC", "Mountain West", "Mountain West Conference", "Mountain West Women"],
    "NEC": ["NEC", "Northeast", "Northeast Conference", "Northeast Women"],
    "Ohio Valley": ["OVC", "Ohio Valley", "Ohio Valley Conference", "Ohio Valley Women"],
    "Patriot": ["Patriot", "Patriot League"],
    "SEC": ["SEC", "Southeastern", "Southeastern Conference", "Southeastern Women"],
    "SoCon": ["SoCon", "Southern", "Southern Conference", "Southern Women"],
    "Southland": ["Southland", "Southland Conference"],
    "SWAC": ["SWAC", "Southwestern Athletic", "Southwestern Athletic Conference"],
    "Summit": ["Summit", "Summit League"],
    "Sun Belt": ["Sun Belt", "Sun Belt Conference", "SBC", "Sun Belt Women"],
    "WAC": ["WAC", "Western Athletic", "Western Athletic Conference"],
    "WCC": ["WCC", "West Coast", "West Coast Conference", "West Coast Women"],
}
